import os
import sys
import json
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader
import mlflow

# Add parent directory to path to import eeg_core
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from eeg_core import load_model, EEGCNN1D

def main():
    script_dir = os.path.dirname(__file__)
    data_dir = os.path.join(script_dir, "data")
    model_dir = os.path.join(script_dir, "../model")
    candidate_dir = os.path.join(script_dir, "../model/candidate")
    os.makedirs(candidate_dir, exist_ok=True)
    
    # 1. Load feedback dataset for validation / train split
    feedback_X_path = os.path.join(data_dir, "feedback_X.npy")
    feedback_y_path = os.path.join(data_dir, "feedback_y.npy")
    if not os.path.exists(feedback_X_path) or not os.path.exists(feedback_y_path):
        print("Error: feedback_X.npy or feedback_y.npy not found. Please run build_feedback_dataset.py first.")
        sys.exit(1)
        
    X_fb = np.load(feedback_X_path)
    y_fb = np.load(feedback_y_path)
    
    n_fb = len(y_fb)
    if n_fb < 5:
        print(f"Warning: Only {n_fb} feedback labels found. Recommended to have at least 5-10 for fine-tuning validation.")
        
    # Split feedback into 80% train, 20% holdout validation
    np.random.seed(42)
    indices = np.arange(n_fb)
    np.random.shuffle(indices)
    split_idx = int(n_fb * 0.8)
    
    train_fb_indices = indices[:split_idx]
    val_fb_indices = indices[split_idx:]
    
    X_fb_train, y_fb_train = X_fb[train_fb_indices], y_fb[train_fb_indices]
    X_val, y_val = X_fb[val_fb_indices], y_fb[val_fb_indices]
    
    # 2. Check if we have merged baseline data
    merged_X_path = os.path.join(data_dir, "merged_X.npy")
    merged_y_path = os.path.join(data_dir, "merged_y.npy")
    
    # We will build our final training set:
    # If we have baseline training data, we use the merged dataset (minus the validation subset of feedback)
    # The merged_X.npy file generated by build_feedback_dataset.py contains base_X + X_fb.
    # To construct the clean train set, we can concatenate the base_X (if present) with X_fb_train.
    # Alternatively, if merged_X.npy is present, we check if it is larger than X_fb.
    X_merged = np.load(merged_X_path)
    y_merged = np.load(merged_y_path)
    
    if len(X_merged) > len(X_fb):
        # We have baseline data merged. Since merged_X contains baseline at the beginning:
        n_base = len(X_merged) - len(X_fb)
        X_base = X_merged[:n_base]
        y_base = y_merged[:n_base]
        # Concat baseline and feedback train
        X_train = np.concatenate([X_base, X_fb_train], axis=0) if len(X_fb_train) > 0 else X_base
        y_train = np.concatenate([y_base, y_fb_train], axis=0) if len(y_fb_train) > 0 else y_base
    else:
        # Train on feedback data train split only
        X_train = X_fb_train
        y_train = y_fb_train
        
    print(f"Training dataset size: {len(y_train)}")
    print(f"Validation dataset size: {len(y_val)}")
    
    # If validation set is empty (e.g. feedback dataset is extremely small), fall back to using train data for val
    if len(y_val) == 0:
        print("Warning: Validation set is empty, reusing training data for evaluation.")
        X_val, y_val = X_train, y_train
        
    # 3. Load baseline model configurations and weights
    print("Loading production model...")
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    # We load production model to get baseline version and weights
    prod_model, prod_mean, prod_std, _, prod_config = load_model(model_dir)
    base_version = prod_config.get("model_version", "v1")
    
    # Clone the model architecture for training
    model = EEGCNN1D(n_channels=prod_config.get("n_channels", 22))
    model.load_state_dict(prod_model.state_dict())
    model.to(device)
    model.train()
    
    # 4. Set up PyTorch loaders
    train_dataset = TensorDataset(torch.tensor(X_train, dtype=torch.float32), torch.tensor(y_train, dtype=torch.long))
    train_loader = DataLoader(train_dataset, batch_size=prod_config.get("batch_size", 8), shuffle=True)
    
    # 5. Fine-tune Training Loop
    epochs = 10
    lr = 1e-4
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()
    
    print(f"Fine-tuning model for {epochs} epochs (learning rate = {lr})...")
    for epoch in range(epochs):
        epoch_loss = 0.0
        correct = 0
        total = 0
        for batch_X, batch_y in train_loader:
            batch_X, batch_y = batch_X.to(device), batch_y.to(device)
            optimizer.zero_grad()
            outputs = model(batch_X)
            loss = criterion(outputs, batch_y)
            loss.backward()
            optimizer.step()
            
            epoch_loss += loss.item() * batch_X.size(0)
            _, predicted = outputs.max(1)
            total += batch_y.size(0)
            correct += predicted.eq(batch_y).sum().item()
            
        avg_loss = epoch_loss / len(train_dataset)
        acc = correct / total
        print(f"Epoch {epoch+1:02d}/{epochs:02d} - Loss: {avg_loss:.4f} - Train Acc: {acc:.4f}")
        
    # 6. Evaluation
    model.eval()
    val_preds = []
    val_probs = []
    
    with torch.no_grad():
        val_X_tensor = torch.tensor(X_val, dtype=torch.float32).to(device)
        outputs = model(val_X_tensor)
        probs = torch.softmax(outputs, dim=1)[:, 1].cpu().numpy()
        preds = outputs.argmax(dim=1).cpu().numpy()
        
    # Calculate Metrics
    TP = np.sum((y_val == 1) & (preds == 1))
    TN = np.sum((y_val == 0) & (preds == 0))
    FP = np.sum((y_val == 0) & (preds == 1))
    FN = np.sum((y_val == 1) & (preds == 0))
    
    recall = float(TP / (TP + FN)) if (TP + FN) > 0 else 0.0
    specificity = float(TN / (TN + FP)) if (TN + FP) > 0 else 0.0
    accuracy = float((TP + TN) / len(y_val)) if len(y_val) > 0 else 0.0
    
    print(f"\nValidation metrics on holdout:")
    print(f"  Accuracy: {accuracy:.4f}")
    print(f"  Recall (Sensitivity): {recall:.4f}")
    print(f"  Specificity: {specificity:.4f}")
    
    # 7. Setup MLflow & Log
    mlflow.set_tracking_uri("sqlite:///mlflow.db")
    mlflow.set_experiment("feedback-retrain")
    
    seizure_labels = int(np.sum(y_fb == 1))
    normal_labels = int(np.sum(y_fb == 0))
    
    # Candidate version update
    try:
        ver_num = int(base_version.replace("v", ""))
        candidate_version = f"v{ver_num + 1}"
    except Exception:
        candidate_version = f"{base_version}_retrained"
        
    with mlflow.start_run(run_name=f"retrain-{candidate_version}"):
        # Log params
        mlflow.log_param("labels_used", n_fb)
        mlflow.log_param("seizure_labels", seizure_labels)
        mlflow.log_param("normal_labels", normal_labels)
        mlflow.log_param("base_version", base_version)
        mlflow.log_param("candidate_version", candidate_version)
        mlflow.log_param("epochs", epochs)
        mlflow.log_param("learning_rate", lr)
        
        # Log metrics
        mlflow.log_metric("test_accuracy", accuracy)
        mlflow.log_metric("test_recall", recall)
        mlflow.log_metric("test_specificity", specificity)
        mlflow.log_metric("feedback_holdout_recall", recall)
        
        # Save temporary files for candidate model artifacts
        candidate_weights_path = os.path.join(candidate_dir, "eegcnn1d_weights.pth")
        candidate_config_path = os.path.join(candidate_dir, "model_config.json")
        candidate_metrics_path = os.path.join(candidate_dir, "test_metrics.json")
        
        torch.save(model.state_dict(), candidate_weights_path)
        
        cand_config = prod_config.copy()
        cand_config["model_version"] = candidate_version
        with open(candidate_config_path, "w") as f:
            json.dump(cand_config, f, indent=2)
            
        cand_metrics = {
            "test_accuracy": accuracy * 100.0,
            "sensitivity": recall,
            "specificity": specificity
        }
        with open(candidate_metrics_path, "w") as f:
            json.dump(cand_metrics, f, indent=2)
            
        # Log artifacts to MLflow
        mlflow.log_artifact(candidate_weights_path)
        mlflow.log_artifact(candidate_config_path)
        mlflow.log_artifact(candidate_metrics_path)
        
        meta_jsonl = os.path.join(data_dir, "feedback_meta.jsonl")
        if os.path.exists(meta_jsonl):
            mlflow.log_artifact(meta_jsonl)
            
        print(f"\nRetraining run logged to MLflow successfully. Candidate version '{candidate_version}' created.")

if __name__ == "__main__":
    main()
